name: example
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  built_config:
  built_config_generator:
    path: ../../built_config_generator

dependency_overrides:
  built_config:
    path: ../../built_config

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  build_runner:
  built_config_generator:
    path: ../../built_config_generator
