name: built_config
description: Annotations for built_config_builder
version: 0.0.5
homepage: https://github.com/hemanthrajv/built_config/tree/master/built_config

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
