targets:
  $default:
    builders:
      todo_reporter_generator|remote_config_data:
        enabled: true

builders:
  remote_config_data:
    target: ":built_config_generator"
    import: "package:built_config_generator/builder.dart"
    builder_factories: ["builtConfigBuilder"]
    build_extensions: {".dart": [".built_config.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]