name: built_config_generator
description: Config Generator
version: 0.0.2
homepage: https://github.com/hemanthrajv/built_config/tree/master/built_config_generator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  source_gen: ^0.9.0
  built_config: ^0.0.1
  build: ^1.0.0
  recase: ^3.0.1
  dart_style:
  built_value: ^7.0.1
  built_collection: ^4.3.2
  code_builder:
  analyzer:
#  path: ^1.7.0

dev_dependencies:
  pedantic:
  test:
  build_test:
  build_runner:
