name: built_config_generator
description: Config Generator
version: 0.0.3
homepage: https://github.com/hemanthrajv/built_config/tree/master/built_config_generator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  source_gen: ^1.2.2
  built_config: ^0.0.2
  build: ^2.3.0
  recase: ^4.0.0
  dart_style: ^2.2.3
  built_value: ^8.4.0
  built_collection: ^5.1.1
  code_builder: ^4.1.0
  analyzer: ^4.3.1
#  path: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  build_test: ^2.1.5
  build_runner: ^2.2.0
