name: built_config_generator
description: Config Generator
version: 0.0.1
homepage: https://github.com/hemanthrajv/built_config/tree/master/built_config_generator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  build:
  source_gen:
  built_config:
    path: ../built_config
  code_builder:
  built_collection:
  built_value:
  dart_style:
  recase:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_test:
  build_runner:
