name: built_config_generator
description: Config Generator
version: 0.0.1+1
homepage: https://github.com/hemanthrajv/built_config/tree/master/built_config_generator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  built_config: ^0.0.1
  build: ^2.0.0
  recase: ^3.0.1
  dart_style: ^2.0.0
  built_value: ^8.0.4
  built_collection: ^5.0.0
  code_builder: ^3.7.0
  analyzer: ^1.4.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_test: ^2.0.0
  build_runner: ^1.12.2
